Bug Fix
Fixed error which caused message 
[+]JrR Jumbo Patch must be used to crack SPNS's
Traceback (most recent call last):
  File "./redsnarf.py", line 2574, in <module>
    print colored("[+]JrR Jumbo Patch installed "+jtr_jumbo_installed()+"\n",'green')
TypeError: cannot concatenate 'str' and 'NoneType' objects